matrix:
  include:
    # Windows
    - os: windows

    # Ubuntu Linux
    - os: linux

    # Mac OSX Latest
    - os: osx
      osx_image: xcode12.2

language: node_js

node_js:
  - lts/*

cache:
  npm: false

install: npm ci