matrix:
  include:
    # Windows
    - os: windows

    # Ubuntu Linux
    - os: linux

    # Mac OSX Latest
    - os: osx
      osx_image: xcode12.2

language: node_js

node_js:
  - lts/*

cache:
  npm: false

install: npm ci

jobs:
  include:
    - stage: "Unit Testing on Mac OS X"
      os: osx
      script: npm test

    - stage: "Unit Testing on Linux"
      os: linux
      script: npm test

    - stage: "Unit Testing on Windows"
      os: windows
      script: npm test

    - stage: "Build if present"
      name: "Running NPM build if present on Mac OS X"
      os: osx
      script: npm run build --if-present

    - stage: "Build if present"
      name: "Running NPM build if present on Linux"
      os: linux
      script: npm run build --if-present

    - stage: "Build if present"
      name: "Running NPM build if present on Windows"
      os: windows
      script: npm run build --if-present