# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Live Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_NAME: 'romanian_jokes'
      DB_COLLECTION: 'jokes'
      DB_URI: ${{ secrets.DB_URI }}
      CI: true

    strategy:
      matrix:
        node: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Get the secret from base64
      run: |
        echo Import certificate from secrets and regenerate the file
        echo $DB_URI | base64 --decode > config

    - run: npm i -f
    - run: npm test
    - run: npm run build --if-present
